### PR TITLE
Added multiple returns for search!

### PR DESCRIPTION
**Pull request by NekaouMike**

### CODE REVIEW

**Comment by JewishLewish** [comment]
Instead of replacing "Search," let's just make another command and call it "Index"

**Comment by NekaouMike** [comment]
That doesn't make sense. Nothing fundamentally changed. It is a enhancement to allow it to return ALL results for a query vs only 1 result for a query. This code could be further modified to take in a limit peramtitor...

**Comment by JewishLewish** [comment]
Problem with the ability to return "ALL results" is that it takes more resources than using Retrieve and searching it with your own code.
So I am going to make it an independent feature.

**Comment by NekaouMike** [comment]
This is not compatible with new binary search. Scrap!

**Pull request closed without merging**
