### PR TITLE
Added multiple returns for search!

### PR DESCRIPTION
**Pull request by NekaouMike**

### CODE REVIEW

**Comment by NekaouMike** [comment]
This will allow for Ploygon to return more than 1 row when doing a search lookup in the DB.

**Comment by JewishLewish** [comment]
Short summary:

This PR updates the search system to output all results instead of just one based on a similar key.

Ex.

```json
{
	"rows": [
		{
			"age": 10,
			"name": "A"
		},
		{
			"age": 20,
			"name": "B"
		},
		{
			"age": 10,
			"name": "C"
		}
	]
}
```

Previously, searching for data with the value ``age:10`` would return the first result.
Output:
```json
{ "Index" : 0, "Value" : {"age":10, "name":"A"}}
```

Mike's suggestion is that it should give the first AND third result since it has the same instead of just the first one.
Output:
```json
{ "Index" : 0, "Value" : {"age":10, "name":"A"}},
{ "Index" : 2, "Value" : {"age":10, "name":"C"}}
```

The problem with this system is that it would the database operate **slower** than doing RETRIEVE then searching it on your own code.

**Comment by JewishLewish** [comment]
@NekaouMike If possible, can I make a separate system called "Index" and let your PR code use that?

**Comment by NekaouMike** [comment]
Can you elaborate on this? Since it is already in the index function.

**Comment by JewishLewish** [comment]
Problem with modifying search is that some people already prefer this ver. of search or are already satisfied with it.

I am confused on why a feature like this is needed or what data you are trying to "search for."

**Comment by JewishLewish** [comment]
@NekaouMike

**Comment by NekaouMike** [comment]
The answer is quite simple.
If you were running a data lookup for statical data say the age of users. Then if you can only get 1 result per age then that's logically flawed if you in reality had 10 users aged 20 and 5 users aged 30. Or in my case and why I needed this in the first place. Looking up the last post an author had or how many posts. There is also NO way of advancing to the following result. Hence why this kind of thing is needed. Most industry people would most likely agree with me on this. Your ONLY argument is seemly "performance" however that's pointless if it barely even functions

**Comment by JewishLewish** [comment]
@NekaouMike 
```
Most industry people would most likely agree with me on this.
```

Please define "Most industry people." 
I don't see any supporting this github discussion? 

```
Your ONLY argument is seemly "performance"...
```
That's because it really is faster perform code on your own local machine then performing it externally. Search takes up the most resources compared to the other actions. 

```
The answer is quite simple.
```
You didn't answer why to replace "Search." You only explained why a feature like this is needed.
Be aware some people use search in a different manner.
Companies make special IDs as a way to differentiate from other people.

**Comment by NekaouMike** [comment]
Well how about this. Go out and find any commonly used data base and see if ANY of them don't return multiple results. If I am right then you should find most if not all DO that. as for "Most industry people." and not contributing to this discussion do you think I am just gonna pull a bunch of top coders who use DBs and have them join here? 

`That's because it really is faster perform code on your own local machine then performing it externally. Search takes up the most resources compared to the other actions.` This statement always annoys me the most as the point of a DB is using it's resources to offload the main app from doing all that it adds up eventually to have the app do it rather than the DB.

`You didn't answer why to replace "Search." You only explained why a feature like this is needed.
Be aware some people use search in a different manner.
Companies make special IDs as a way to differentiate from other people.`
the feature can still be used both ways and making it 2 separate features is just outright annoying and makes no sense since it takes 1 line of code to basically revert it on the user end. Also you would still need the info on each ID which just invalidates this.

**Comment by JewishLewish** [comment]
```
Also you would still need the info on each ID which just invalidates this.
```

A) People usually design user's data like this. (Github's api does the same thing to.)
```json
{
"0001" : {
   "name" : "Michael",
   "age": 20
   }, 
"0002" : {
   "name" : "Tite",
   "age": 18
   }
}
```

Ex. https://api.github.com/users/JewishLewish

B) Even if I were to design my data in a list. Then all I need is just one person's account not a collection of them.
Again, a lot of companies (even github) designed it so you have your own unique github id. 

If I am going onto my own github page (https://github.com/JewishLewish), then github isn't going to display other's people data other than my own. 

C) In your standard, I completely understand why you prefer your way of collecting data. However, that isn't going to justify replacing Search's code.

**Review by JewishLewish — APPROVED** [review]
Should work as expected.

**Comment by JewishLewish** [comment]
Merging.

I am going to make "index" and "search" separate for now.
Since the discussion revolving the feature is very *small* and would require more people's perspective and opinions...
It's best to include both features for now and re-open this discussion in the future.

Thank you for your assistance.

**Pull request merged**
